# Datasource Configuration
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:ckpanda}?characterEncoding=utf8
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:l3tm3in}
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 3625000
        validationQuery: SELECT 1


    jpa:
        hibernate.ddl-auto: validate

        # Specify the DBMS
        database: MYSQL

        # Show or not log for each sql query
        show-sql: true

        # Hibernate settings are prefixed with spring.jpa.hibernate.*
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
            show_sql: true
            format_sql: true

    # RabbitMQ Properties
    rabbit:
        host: ${RABBITMQ_HOST}
        vhost: /
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
        exchange:
            name: ${RABBITMQ_EXCHANGE}
        email:
            name: ${RABBITMQ_EMAIL_EXCHANGE}
    # CS server Routing key
        server:
            action:
                pattern: "*.ActionEvent.*.*.*"
                queue: ${RABBITMQ_ACTION_EVENT}
            alert:
                pattern: "*.AlertEvent.*.*.*"
                queue: ${RABBITMQ_ALERT_EVENT}
            usage:
                pattern: "*.UsageEvent.*.*.*"
                queue: ${RABBITMQ_CS_USAGE_EVENT}
            asynchJob:
                pattern: "*.AsyncJobEvent.*.*.*"
                queue: ${RABBITMQ_CS_ASYNC_EVENT}
            resource:
                pattern: "*.ResourceStateEvent.*.*.*"
                queue: ${RABBITMQ_RESOURCE_EVENT}
            email:
                pattern: "email.template"
                queue : ${RABBITMQ_EMAIL}
 # Mail configuration
    mail:
        host: mail.xxx.com
        port: 25
        username: xxx@xxx.com
        password: xxx
        properties:
            mail:
                smtp:
                    auth: true
                starttls:
                    enable: true
                    required: true

    template:
        view:
            prefix: file:/var/log/
            suffix: .html

#Payment page
    view:
        prefix: /jsp/
        suffix: .jsp
---

cloudstack:
    url: ${CLOUDSTACK_URL}
console:
    proxy: ${CONSOLE_URL}
mrping:
    url: ${MRPING_URL}

---

app:
    buildversion: ${APP_BUILD_NUMBER:"1.0"}


logging:
    level:
        org:
            springframework.web: TRACE

---

server:
    port: ${PANDA_PORT:8080}
    session-timeout: 60

---

security:
    basic:
        enabled: false

---

endpoints:
    shutdown:
        enabled: true
---

flyway:
    initOnMigrate: true
---


keystore:
    file: src/main/resources/private/keystorejks
    pass: password

---

backend:
    admin:
        userid: 1
        username: ${BACKEND_ADMIN_USERNAME}
        password: ${BACKEND_ADMIN_PASSWORD}
        role: BACKEND_ADMIN
        dominid: 1
        departmentid: 1000
        type: 1
        userapikey: kUDWhIgso-UXTaAQulvgqidAbsC4gFCssPPFYWppiGsvSGbnO8_A2f4G8svqCnwyMcp6zCrrwvDQNVTtIqnTfA
        usersecretkey: Lv2Fl5mc4C5g_qGYNWLCTprKUx1DDFBQiFwLg5JVYMamehm20IT3iPgk5CtUtzxMtcSdAgbZ1VFJWcX56R0iGw

---

error:
    whitelabel:
        enabled: false

---

#Pagination properties
pagination:
    limit: 10

---

#Mon Oct 26 09:13:02 IST 2015
aes:
    salt:
        secretKey: DA97AA70B21ADCCA89708EFC05C7E2F2

---

#Login timeout
login:
    timeout:
        inmilliseconds: ${LOGIN_TIMEOUT}

english:
    template:
        dir: ${ENGLISH_TEMPLATE_DIR}
chinese:
    template:
        dir: ${CHINESE_TEMPLATE_DIR}
invoice:
    base:
        path: ${INVOICE_ATTACHMENT_DIR:/home/Assistanz/invoice/invoiceattachment}

---
payment:
    return:
        url: ${PAYMENT_RETURN_URL:http://localhost:9090/pandaui/login}

---
background:
    logo:
        dir: ${BACKGROUNG_LOGO_PATH}

